// <auto-generated />
namespace ASP_MVC_Demo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RevertedChangeOfAnimalTypeToEnum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RevertedChangeOfAnimalTypeToEnum));
        
        string IMigrationMetadata.Id
        {
            get { return "202208081005183_RevertedChangeOfAnimalTypeToEnum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
